### DISCUSSION TITLE
Automate the closing of abandoned repo issues

### DISCUSSION THREAD

**Discussion by blackfalcon** [AlaskaAirlines/WC-Generator#537] [Announcements]
## The problem

Management of inactive issues is labor-intensive and largely ignored. 

- Issue Inactivity: The management of inactive issues is labor-intensive and often overlooked.
- Missing Information: A significant challenge arises from issues that lack essential information required for problem reproduction. Despite multiple attempts by the author to provide additional details, feedback remains minimal.
- Recourse: When faced with unresolved issues, the only available option is to close them.

## The recommendation 

- Pattern from Auro Library: Following the pattern established by the Auro Library, all repositories should adopt a new GitHub action.
- GitHub Action Script Modifications:
  - Scheduled Execution: The action runs on a weekly schedule (every Monday at midnight).
  - Staleness Thresholds:
    - Issues become stale after 90 days of inactivity.
    - Issues are automatically closed if they remain inactive for 30 days after being marked as stale.
  - Communication with Authors:
    - A “stale” label is applied to inactive issues.
    - A message informs authors that their issue is stale due to 90 days of inactivity.
    - If an issue is closed, the author is encouraged to contact the Auro team for reinstatement if they believe the closure was inappropriate.
  - Pull Requests (PRs):
    - PRs are not considered for staleness.
    - PRs are not automatically closed.
  - Permissions and Token: The action runs on the latest Ubuntu environment and requires permissions for writing issues and pull requests. It uses the repository token stored in GitHub secrets.

Using the pattern we have started with Auro Library, all repos will subscribe to a new Github action that uses the following [recommended script from Github](https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues) with the following modifications.

```yml
name: Close inactive issues
on:
  schedule:
    - cron: "0 0 * * mon"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 90
          days-before-issue-close: 30
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 90 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 30 days since being marked as stale. If the author feels this issue was inappropriately closed, don't hesitate to contact the Auro team for reinstatement."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```

## Outcomes and expectations 

- Efficiency: Automating issue closure reduces manual effort and streamlines the process.
- Timely Resolution: Issues are addressed promptly, preventing prolonged inactivity.
- Clear Communication: Authors receive clear messages about issue status and potential closure.
- Consistency: The approach ensures uniformity across repositories.
- Improved Collaboration: Authors can engage with the Auro team for issue reinstatement if needed.

Remember, this recommendation aims to enhance issue management and foster a more efficient and responsive development process
