### DISCUSSION TITLE
BETA Release config and process

### DISCUSSION THREAD

**Discussion by blackfalcon** [AlaskaAirlines/WC-Generator#556] [General Auro discussions]
# BETA Release config and process

## Problem

The current build and release process, designed for environments supporting rapid continuous delivery and deployment, has become a challenge for Auro as it has matured. Instead of providing an advantage, it has turned into a distraction.

Teams have expressed concerns about the frequent release of updates that are incompatible with other component versions and insufficient regression testing. Additionally, there is feedback that rapid updates cause issues for development teams that typically review dependencies only quarterly.

To address these issues, the team created a Release Candidate (RC) process to bundle multiple updates into a single release. However, the constraints of this RC development process necessitated releasing updates before they were fully tested. Furthermore, updates in an RC were unusable until the entire feature set was officially released.

## Recommendation

To resolve these issues, we recommend a two-part solution: revive the previous RC development process and implement a new BETA package release process.

1. **Revive and Enhance the RC Process**:
   - Reinstate the RC development process to bundle updates and deploy them in a single release.
   - Ensure updates are thoroughly tested before being released from the RC.

2. **Implement a BETA Package Release Process**:
   - Introduce a permanent `beta` branch alongside the `main` branch in the repository.
   - As new code is merged into the `beta` branch, the Semantic Release process will generate a new BETA versioned release.

BETA releases will be clearly communicated to the organization as preliminary versions that may contain issues. These versions will be labeled as "use at your own risk" until fully tested and deemed ready for official release.

Development teams will be encouraged to use BETA versions with the understanding that there may be issues or compatibility concerns with other Auro components.

This proposed BETA process will include the following updates:

- Clear documentation and communication regarding the nature and purpose of BETA releases.
- Encouragement for teams to test BETA versions in their environments to identify and report issues early.
- A structured feedback mechanism to address and resolve any problems identified in BETA releases before official deployment.

### Auro Doc Site page 

There is to be a new page added to the doc site for developer education about the BETA process. This document will explain the full process of BETA development, define timelines and testing processes for code going from BETA to Prod release, and provide information on how to install, test, and submit issues for BETA versions of code. 

### Repo config 

Repo configuration for BETA releases requires the following steps: 

1. Create a new branch, `beta`, from the `main` branch. Publish the new branch.
1. On the `main` branch edit the `./package.json` file, see Figure 1 below.
1. On the `main` branch edit the `./.github/workflows/testPublish.yml` file, see Figure 2 below.
1. On the `main` branch edit the `./.github/settings.yml` file, see Figure 3 below.
1. Push the changes into the `main` branch with a `build` commit and publish code.
1. Once published, REBASE the `beta` branch on `main` and `--force` publish.

##### Figure 1

Update the `./package.json` `release` object so that Semantic Release knows there is a new `beta` branch and that it's allowed to pre-release updated versions.

```

// Find the following code
// Be sure to use MAIN or MASTER, whichever the head branch is for that repo

  "release": {
    "branch": "main",
    ...
  }
  
// Update to the following

  "release": {
    "branches": [
      {
        "name": "main"
      },
      {
        "name": "beta",
        "prerelease": true
      }
    ],
    ...
  }
```

##### Figure 2

Update the `./.github/workflows/testPublish.yml` file to include the `beta` branch when evaluating releases. 

```
// Find the following code
// Be sure to use MAIN or MASTER, whichever the head branch is for that repo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

// Update to the following

on:
  push:
    branches: [ main, beta ]
  pull_request:
    branches: [ main, beta ]
```

Also... 

```

// Find the following code

if: github.event_name == 'push' && github.ref == 'refs/heads/main'

// Update to the following

if: github.event_name == 'push' && github.ref == 'refs/heads/main' || 'refs/heads/beta'

```

##### Figure 3

Update the `./.github/settings.yml` file to add branch protection for `beta`. 

```yaml

// find the following code

branches:
  - name: main
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 1
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: true
        # Required. Require status checks to pass before merging. Set to null to disable
        # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
        dismissal_restrictions:
          users: ["blackfalcon"]
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        contexts: ["test (18.x)", "test (20.x)", "license/cla"]
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: false
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions: null
      # Prevent merge commits from being pushed to matching branches
      required_linear_history: true
      

// replace with the following

branches:
  - &default_protection
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 1
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: true
        # Required. Require status checks to pass before merging. Set to null to disable
        # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
        dismissal_restrictions:
          users: ["blackfalcon"]
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        contexts: ["test (18.x)", "test (20.x)", "license/cla"]
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: false
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions: null
      # Prevent merge commits from being pushed to matching branches
      required_linear_history: true

  - name: main
    <<: *default_protection

  - name: beta
    <<: *default_protection

```

##### Non SemVer process 

While the BETA release process is widely supported, the BETA npm version type, e.g. `1.0.0-beta.4` is not officially supported by SemVer. 

This means that some automated tools MAY NOT easily support the installation or updating of these BETA releases. To some extent this is to be expected as using BETA releases should be a task that requires manual intervention as an acknowledgment of the scenario. 

##### Updated repos

List of completed repos. 

|Repo|commit
|---|--- 
|WC-Generator repo|https://github.com/AlaskaAirlines/WC-Generator/pull/559/commits/b2fba31a9630621680e9ff0234f28e2579eba4fa
|WC-Generator template|https://github.com/AlaskaAirlines/WC-Generator/pull/559/commits/b2fba31a9630621680e9ff0234f28e2579eba4fa
|WCSS| https://github.com/AlaskaAirlines/WebCoreStyleSheets/pull/195/commits/58d3f7beedac8908ac4286c5a90d0c276df50c20
|Library| https://github.com/AlaskaAirlines/auro-library/pull/53/commits/694b2aa2122bc210c616e9ee0bf7eaabfa79ef75
|icons| https://github.com/AlaskaAirlines/Icons/pull/254/commits/149fcd623fef3542e8abf3d98c0ed07eb985ce15
|auro-skeleton|https://github.com/AlaskaAirlines/auro-skeleton/commit/51ab82df3fe3221f60a554124d99b935900dd732
|auro-table|https://github.com/AlaskaAirlines/auro-table/commit/72d3d01766c1be8967a5fcca924230f86c5c5678
|auro-toast|https://github.com/AlaskaAirlines/auro-toast/commit/23bb147a5fcb8f88f3da0656cb913809a0002535
|auro-pane|https://github.com/AlaskaAirlines/auro-pane/commit/8b3d8562424937158aa88e78bf5c88da61b24da5
|auro-datetime|https://github.com/AlaskaAirlines/auro-datetime/commit/96f0741a409c249b07a029e772ba87a67c2be70b
|auro-popover|https://github.com/AlaskaAirlines/auro-popover/commit/166415e90bd5e0951dfb100df12be59d7df74d66
|auro-radio|https://github.com/AlaskaAirlines/auro-radio/commit/cd0fa9c6915a4818b0a6865de5232d2950b0c31f
|auro-loader|https://github.com/AlaskaAirlines/auro-loader/commit/d3e4371f18d5dd04fc536ab78ab3fda955174ab8
|auro-dialog|  https://github.com/AlaskaAirlines/auro-dialog/commit/bfd236081898e2618ed3f6df3a53af77e296b9db
|auro-drawer|https://github.com/AlaskaAirlines/auro-drawer/commit/6ab40e070a54afab42882a0e18a73c94124112a5
|auro-header|https://github.com/AlaskaAirlines/auro-header/commit/72fe39b89c035d7a94bad027aae7abc8b34850dd
|auro-dropdown| https://github.com/AlaskaAirlines/auro-dropdown/commit/95be7d83b9a65a114e45d060fbaa4cceadcab3e6
|auro-alert|https://github.com/AlaskaAirlines/auro-alert/commit/178b1eadcfd95b88d2e92b6e11cbfe31968f17f4 
|auro-badge|https://github.com/AlaskaAirlines/auro-badge/commit/5c81c0b4d00ce0130a9d5985fe86dedbe8ab567f
|auro-hyperlink| https://github.com/AlaskaAirlines/auro-hyperlink/commit/96618e1716fd7a8626392a66e4af4ee985fac230
|auro-icon| https://github.com/AlaskaAirlines/auro-icon/commit/8ef24c913581a92a6b9ef63e13cd2dc0b2f407fd
|auro-menu| https://github.com/AlaskaAirlines/auro-menu/commit/46050b8aabc10ffb11b34dbd21409901620d98c5
|auro-lockup| https://github.com/AlaskaAirlines/auro-lockup/commit/35ac65d999d21e2ea4febd13db7ccbaf4ab46082
|auro-avatar| https://github.com/AlaskaAirlines/auro-avatar/commit/6ac1e4435ec3c9ffbcca5b1944d20b6aea1336de and https://github.com/AlaskaAirlines/auro-avatar/commit/f58eeadc5b3738f96461960161a83bf028516cb2
|auro-flight|https://github.com/AlaskaAirlines/auro-flight/commit/1eae27e47aed42f941909285043ab8649812b026
|auro-input|https://github.com/AlaskaAirlines/auro-input/commit/c2fc1c4b2296eb2c6799c3d5b8cc1c68d7c0dc6b
|auro-backtotop|https://github.com/AlaskaAirlines/auro-backtotop/commit/80a796b7bc48585dc05423620dc216456a6d8aa8
|auro-select|https://github.com/AlaskaAirlines/auro-select/commit/3a89bb1100dc6171d252f40fdaa7a3a57f8d1cc3
|auro-accordion|https://github.com/AlaskaAirlines/auro-accordion/commit/7458c7f0ccc4d18c954b067429aaa6753dfa2dc4
|auro-card|https://github.com/AlaskaAirlines/auro-card/commit/68a8d9dade4a282fc4f2dfef058760debe44edec
|auro-checkbox|https://github.com/AlaskaAirlines/auro-checkbox/commit/99f38476094648fe1a3eb7758b17ed69b44e33ea
|auro-carousel|https://github.com/AlaskaAirlines/auro-carousel/commit/78a19472cae25af1d4d843991b6f9e6871f635af 
|auro-formvaliator|https://github.com/AlaskaAirlines/auro-formvalidation/commit/d119fe2cca3abff2c53cbedf22e01fcdd35a816d
|auro-flightline| https://github.com/AlaskaAirlines/auro-flightline/commit/7b5a743dc2a991e3c4ce2f74d60fc46485e7cadc
|auro-nav|  https://github.com/AlaskaAirlines/auro-nav/commit/0e37d2fe1400a4e11c89ede81908df94720dbc51
|auro-sidenav| https://github.com/AlaskaAirlines/auro-sidenav/commit/f2439a4a4993fe64b4701d1f49c530e8dd8089d4
|auro-combobox|  https://github.com/AlaskaAirlines/auro-combobox/commit/47f543908717917fa8b74cce1d963c5b6ebb8353
|auro-datepicker| https://github.com/AlaskaAirlines/auro-datepicker/commit/e5d739f78a20dbd796c1fc9c7111ec723ea6e7d5
|auro-button|https://github.com/AlaskaAirlines/auro-button/commit/1e4e4fb3a2f1a960484cef3621a75e0a5b7a89c2
|auro-background|  https://github.com/AlaskaAirlines/auro-background/commit/544d06061d8e116f65471bf93f3518ed65e80fe9
|auro-banner|  https://github.com/AlaskaAirlines/auro-banner/commit/7182414ee35555f2da08dba7547f9813e2d24eab

**Script for commit:** 

build: add BETA release support

This commit updates the repo's build scripts to be compliant with
BETA releases described in this discussion:

https://github.com/orgs/AlaskaAirlines/discussions/556

### Process

The BETA release process will resemble much of the well-known [git flow](https://www.gitkraken.com/learn/git/git-flow), but only requires the `beta` branch in place of the `develop` branch. 

> The [beta] branch should be used when preparing new production releases. Typically, the work being performed on [beta] branches concerns finishing touches and minor bugs specific to releasing new code, with code that should be addressed separately from the main development branch.

The BETA process will mean that NO FEATURE branches are ever created from `main`, but always from `beta`. 

> The feature branch is the most common type of branch in the Git flow workflow. It is used when adding new features to your code.
>
> When working on a new feature, you will start a feature branch off the [beta] branch, and then merge your changes back into the [beta] branch when the feature is completed and properly reviewed.

Conversely, bug fixes will require following the git flow [hot fix](https://www.gitkraken.com/learn/git/git-flow#git-flow-hotfix-branch) process. 

> In Git flow, the hotfix branch is used to quickly address necessary changes in your main branch.
>
> The base of the hotfix branch should be your main branch and should be merged back into both the main and develop branches. Merging the changes from your hotfix branch back into the develop branch is critical to ensure the fix persists the next time the main branch is released.

**It should be noted that the BETA process SHOULD NOT be used as a way to release an incomplete concept quickly. All merges into BETA should be considered READY FOR PROD at any moment.** 

## Expected outcomes 

Implementing the proposed updates is expected to yield several key outcomes:

1. **Improved Stability and Compatibility**:
   - By reinstating the RC process and ensuring thorough testing before release, updates will be more stable and compatible with other components.
   - Fewer incidents of incompatibility and regression issues, resulting in smoother integration and fewer disruptions for development teams.

3. **Enhanced Quality Assurance**:
   - The introduction of a BETA package release process will provide an additional layer of testing.
   - Early identification and resolution of bugs and issues will lead to higher-quality releases.

4. **Increased Flexibility for Development Teams**:
   - Teams can choose to adopt BETA versions to access new features early, allowing for more flexibility in development cycles.
   - This approach accommodates teams that review dependencies infrequently, aligning better with their workflows.

5. **Better Risk Management**:
   - Clear communication that BETA versions are "use at your own risk" will help manage expectations and encourage cautious adoption.
   - Teams can test BETA releases in controlled environments before full deployment, mitigating potential risks.

6. **More Efficient Release Management**:
   - Bundling updates in RCs will streamline the release process, reducing the overhead associated with frequent, smaller updates.
   - More predictable release schedules will improve planning and coordination across teams.

7. **Enhanced Collaboration and Feedback Loops**:
   - Encouraging the use of BETA versions will foster a more collaborative environment, where teams provide feedback and contribute to improving the final release.
   - Structured feedback mechanisms will ensure that issues are promptly addressed, leading to continuous improvement.

8. **Reduced Disruption and Increased Productivity**:
   - Minimizing disruptive, incompatible updates will allow teams to focus on their core tasks without frequent interruptions.
   - Overall productivity is expected to increase as development teams experience fewer unexpected issues and smoother integration processes.

9. **Clearer Communication and Documentation**:
   - Clear documentation of the BETA process and expected use will improve understanding and adoption across the organization.
   - Better communication regarding the nature and purpose of BETA and RC releases will align team expectations and practices.

These outcomes collectively aim to enhance the efficiency, stability, and quality of the build and release process, ultimately supporting the organization's goals and development practices.
