### ISSUE TITLE
Automate new label per repo

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/WC-Generator#205]
## Is your feature request related to a problem? Please describe.

There are new labels that do not exist in the current repos. 

## Describe the solution you'd like

Add the new labels to the template repo in the generator (settings.yml)

```
  - name: auro-[name]
    cat: default
    color: fa23e4
    description:
    process: Apply to issues to identify project repo
  - name: Release
    cat: default
    color: 1c872e
    description: Defines release scope of work
    process: Apply to any issue that is the designated parent issue for a release
  - name: Issue
    cat: default
    color: 1c872e
    description: Defines issue scope of work related to release
    process: Apply to any issue that is associated to a release
```
