### ISSUE TITLE
Automate the closing of abandoned repo issues

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/WC-Generator#538]
### Discussed in https://github.com/orgs/AlaskaAirlines/discussions/537

<div type='discussions-op-text'>

<sup>Originally posted by **blackfalcon** April 12, 2024</sup>
Management of inactive issues is labor-intensive and largely ignored. 
</div>

## The recommendation 

Following [this pattern](https://github.com/AlaskaAirlines/WC-Generator/blob/master/template/.github/workflows/addToProject.yml) of development, add a new script reference for the new `closeInactiveIssues.yml` file. 

1. Add new code to auro-library, feature update/release
2. Add new code to wc-generator template, feature update/release
3. Add new code to all Auro repos*, build/CI update, no feature release

Location - `wc-generator/template/.github/workflows/closeInactiveIssues.yml`
Location - all Auro repos*

```yml
name: Close inactive issues

on:
  schedule:
    - cron: "0 0 * * mon"

jobs:
  call-issue-close-workflow:
    uses: AlaskaAirlines/auro-library/.github/workflows/closeInactiveIssues.yml@main
    secrets: inherit
```

Location-`auro-library/.github/workflows/addToProject.yml`

```yml
name: Close inactive issues

on:
  workflow_call:

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 90
          days-before-issue-close: 30
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 90 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 30 days since being marked as stale. If the author feels this issue was inappropriately closed, don't hesitate to contact the Auro team for reinstatement."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```

#### *Update repos

Individual issues per repo is NOT necessary. Please update the table below with a link to the commit from each repo. Highly recommend creating a script that will automate the updating of the repos.

| Repo | Commit |
|---|---
|auro-library|
|auro-alert | 
| auro-drawer |
| auro-hyperlink |
| auro-lockup |
| auro-flight |
| auro-dialog |
| auro-banner |
| auro-card |
| auro-nav |
| auro-datepicker |
| auro-popover |
| auro-dropdown |
| auro-radio |
| auro-checkbox |
| auro-button |
| auro-loader |
| auro-flightline |
| auro-backtotop |
| auro-combobox |
| auro-carousel |
| auro-table |
| auro-toast |
| auro-icon |
| auro-select |
| auro-sidenav |
| auro-pane |
| auro-header |
| auro-datetime |
| auro-input |
| auro-avatar |
| auro-badge |
| auro-background |
| auro-interruption |
| auro-skeleton |
| auro-menu |

## Exit criteria 

This issue can be close once it can be demonstrated that the resource files have been added to the generator template, the auro-library repo and each individual element repo has been updated with the new workflow.
